### PR TITLE
refactor: Centralise BigNumber imports

### PR DESCRIPTION
**Pull request by pxrl**
Avoid importing BigNumber from ethers directly throughout the repository, and instead just re-export the standalone ethers BigNumber variant from src/utils/BigNumberUtils. This should make it easier to migrate away from ethers v5.

### CODE REVIEW

**Review by nicholaspai — APPROVED** [review]
This is awesome work! So now we only have a single Bn import from ethers?

**Comment by pxrl** [comment]
> This is awesome work! So now we only have a single Bn import from ethers?

Yeah, hopefully this achieves that. It's a bit tricky to be 100% sure but I've eliminated as many cases of importing directly from ethers as I could identify. If we implement a BigInt -> BigNumber shim then we might be able to play with v6.

**Review by dohaki — APPROVED** [review]
Nice work! I think this shouldn't break anything on the FE AFAICT. Also really like @gsteenkamp89 suggestion

**Review by gsteenkamp89 — APPROVED** [review]
nice one! this will help for sure :)

**Pull request merged**
